const card = [
    {   id: 1,
        pair_id: 2, 
        name: '',
        src: '',
    },
    {   id: 2,
        pair_id: 1, 
        name: '',
        src: '',
    },
    {   id: 3,
        pair_id: 4, 
        name: '',
        src: '',
    },
    {   id: 4,
        pair_id: 3, 
        name: '',
        src: '',
    },
    {   id: 5,
        pair_id: 6, 
        name: '',
        src: '',
    },
    {   id: 6,
        pair_id: 5, 
        name: '',
        src: '',
    },
    {   id: 7,
        pair_id: 8, 
        name: '',
        src: '',
    },
    {   id: 8,
        pair_id: 7, 
        name: '',
        src: '',
    },
    {   id: 9,
        pair_id: 10, 
        name: '',
        src: '',
    },
    {   id: 10,
        pair_id: 9, 
        name: '',
        src: '',
    },
    {   id: 11,
        pair_id: 12, 
        name: '',
        src: '',
    },
    {   id: 12,
        pair_id: 11, 
        name: '',
        src: '',
    },
    {   id: 13,
        pair_id: 14, 
        name: '',
        src: '',
    },
    {   id: 14,
        pair_id: 13, 
        name: '',
        src: '',
    },
    {   id: 15,
        pair_id: 16, 
        name: '',
        src: '',
    },
    {   id: 16,
        pair_id: 15, 
        name: '',
        src: '',
    }
]
module.exports  = members